import random

class Tiles:
    def __init__(self, letter, value):
        self.letter = letter
        self.value = value

class BagTiles:
    def __init__(self):
        self.tiles = [
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('A', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('E', 1),
            Tiles('O', 1),
            Tiles('O', 1),
            Tiles('O', 1),
            Tiles('O', 1),
            Tiles('O', 1),
            Tiles('O', 1),
            Tiles('O', 1),
            Tiles('O', 1),
            Tiles('O', 1),
            Tiles('I', 1),
            Tiles('I', 1),
            Tiles('I', 1),
            Tiles('I', 1),
            Tiles('I', 1),
            Tiles('I', 1),
            Tiles('S', 1),
            Tiles('S', 1),
            Tiles('S', 1),
            Tiles('S', 1),
            Tiles('S', 1),
            Tiles('S', 1),
            Tiles('N', 1),
            Tiles('N', 1),
            Tiles('N', 1),
            Tiles('N', 1),
            Tiles('N', 1),
            Tiles('L', 1),
            Tiles('L', 1),
            Tiles('L', 1),
            Tiles('L', 1),
            Tiles('R', 1),
            Tiles('R', 1),
            Tiles('R', 1),
            Tiles('R', 1),
            Tiles('R', 1),
            Tiles('U', 1),
            Tiles('U', 1),
            Tiles('U', 1),
            Tiles('U', 1),
            Tiles('U', 1),
            Tiles('T', 1),
            Tiles('T', 1),
            Tiles('T', 1),
            Tiles('T', 1),
            Tiles('D', 2),
            Tiles('D', 2),
            Tiles('D', 2),
            Tiles('D', 2),
            Tiles('D', 2),
            Tiles('G', 2),
            Tiles('G', 2),
            Tiles('C', 3),
            Tiles('C', 3),
            Tiles('C', 3),
            Tiles('C', 3),
            Tiles('B', 3),
            Tiles('B', 3),
            Tiles('M', 3),
            Tiles('M', 3),
            Tiles('P', 3),
            Tiles('P', 3),
            Tiles('H', 4),
            Tiles('H', 4),
            Tiles('F', 4),
            Tiles('V', 4),
            Tiles('Y', 4),            
            Tiles('Q', 5),
            Tiles('J', 8),            
            Tiles('Ñ', 8),            
            Tiles('X', 8),
            Tiles('Z',10),
            Tiles('CH',5),
            Tiles('LL',8),
            Tiles('RR',8),
            Tiles('?', 0),
            Tiles('?', 0),
        ]
        random.shuffle(self.tiles)
    
    def take(self, count):
        tiles = []
        for _ in range(count):
            tiles.append(self.tiles.pop())
        return tiles
    
    def put(self, tiles):
        self.tiles.extend(tiles)
